# roles/haproxy/tasks/tests.yml
#---     
- name: wait ha proxy stat
  wait_for:
    port: 9000
- name: wait ha proxy lb
  wait_for:
    port: 80
- name:  ensure  home    page    returns 200
  uri:
    url: http://127.0.0.1:9000/

