# install.yml   
#---     

- hosts: app-servers                  
  gather_facts: false                   
  tasks:                    
  - name: install tomcat
    package:
      name: tomcat8
  - name: start/enable Tomcat
    service:
      name: tomcat8
      enabled: true
      state: started
  - name: verif http port
    wait_for:
      port: 8080
  - name:  ensure  home    page    returns 200 
    uri:
      url: http://127.0.0.1:8080/
